=== Team302/mainRepotest/src/main/config/robot.dtd
<!ELEMENT robot (pdp?, pigeon?, limelight?, camera*, blinkin*, swervechassis?, mechanism* )>

<!ELEMENT pdp EMPTY>
<!ATTLIST pdp 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
>

<!ELEMENT pigeon EMPTY>
<!ATTLIST pigeon 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
          rotation CDATA "0.0"
>

<!ELEMENT limelight EMPTY>
<!ATTLIST limelight 
		  tablename         ( limelight | limelight2 ) "limelight"
		  mountingheight    CDATA #REQUIRED
		  horizontaloffset  CDATA "0.0"
		  mountingangle     CDATA #REQUIRED
		  rotation          ( 0.0 | 90.0 | 180.0 | 270.0 ) "0.0"
		  targetheight      CDATA #REQUIRED
		  targetheight2     CDATA #REQUIRED
		  defaultledmode	( currentpipeline | off | blink | on ) " currentpipeline" 
		  defaultcammode    ( vision | drivercamera ) "vision"
		  streammode        ( sidebyside | pipmain | pipsecondary ) "sidebyside"
		  snapshots         ( off | twopersec ) "off"
		  crosshairx        CDATA #IMPLIED
		  crosshairy        CDATA #IMPLIED
		  secondcrosshairx  CDATA #IMPLIED
		  secondcrosshairy  CDATA #IMPLIED
>


<!ELEMENT camera EMPTY>
<!ATTLIST camera 
          id                CDATA "0"
          format            ( KMJPEG| KYUYV | KRGB565 | KBGR | KGRAY ) "KMJPEG"
          width			 	CDATA "640"
          height		 	CDATA "480"
          fps			 	CDATA "30"
		  thread            ( true | false ) "false"
>

<!ELEMENT blinkin EMPTY>
<!ATTLIST blinkin 
		  position				( front | back | top | bottom ) "front"
          pwmId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 ) "0"
>





<!-- ========================================================================================================================================== -->
<!--	swerve chassis  																																-->
<!--    Wheel Base is front-back distance between wheel centers  Track is the distance between wheels on an "axle"     							-->   
<!-- ========================================================================================================================================== -->
<!ELEMENT swervechassis (swervemodule*) >
<!ATTLIST swervechassis 
          type              ( SWERVE ) "SWERVE"
          wheelDiameter                     CDATA #REQUIRED
          wheelBase                         CDATA #REQUIRED
          track                             CDATA #REQUIRED
          odometryComplianceCoefficient     CDATA "1.0"
          maxVelocity                       CDATA #REQUIRED
          maxAngularVelocity                CDATA #REQUIRED
          maxAcceleration                   CDATA #REQUIRED
          maxAngularAcceleration            CDATA #REQUIRED
>

<!ELEMENT swervemodule (motor*, cancoder? ) >
<!ATTLIST swervemodule 
          type              ( LEFT_FRONT | RIGHT_FRONT | LEFT_BACK | RIGHT_BACK ) "LEFT_FRONT"
          turn_p            CDATA "0.0"
          turn_i            CDATA "0.0"
          turn_d            CDATA "0.0"
          turn_f            CDATA "0.0"
          turn_nominal_val  CDATA "0.0"
          turn_peak_val     CDATA "1.0"
          turn_max_acc      CDATA "0.0"
          turn_cruise_vel   CDATA "0.0"
>


<!-- ========================================================================================================================================== -->
<!--	mechanism  																																-->
<!-- ========================================================================================================================================== -->
<!ELEMENT mechanism (motor*, solenoid*, servo*, digitalInput*, cancoder*)>
<!ATTLIST mechanism
          type              ( INTAKE | BALL_TRANSFER | SHOOTER | TURRET | BALL_HOPPER ) "INTAKE"
>

<!ELEMENT solenoid EMPTY >
<!ATTLIST solenoid 
		  usage 			( INTAKE | HUMAN_PLAYER_FLAP | BALL_TRANSFER | SHOOTER_HOOD | CONTROL_TABLE_MANIPULATOR | CLIMBER ) "INTAKE"
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
          channel           (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 ) "0"
          reversed          (true | false ) "false"
>
<!ELEMENT servo EMPTY>
<!ATTLIST servo 
          usage             (  SHOOTER_HOOD ) "SHOOTER_HOOD"
          pwmId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 ) "0"
          minAngle			CDATA "0.0"
          maxAngle          CDATA "360.0"
>


<!-- ========================================================================================================================================== -->
<!-- 	shared items				 																											-->
<!-- ========================================================================================================================================== -->


<!-- motor  -->
<!-- ========================================================================================================================================== -->
<!--       Gear Ratio  =   rotations of driver gear  /   rotations of driven gear =      teeth of driven gear   / teeth of driver gear          -->
<!-- ========================================================================================================================================== -->
<!ELEMENT motor (digitalInput*)>
<!ATTLIST motor 
          usage             	    ( DRIVE  | TURN  |
                                      INTAKE | BALL_TRANSFER | TURRET | 
                                      SHOOTER_1 | SHOOTER_2 | SHOOTER_HOOD | BALL_HOPPER ) "DRIVE"
          canId             		(  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              		  10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              		  20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              		  30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              		  40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              		  50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              		  60 | 61 | 62 ) "0"
		  pdpID						CDATA #IMPLIED
          type              		( TALONSRX | FALCON  ) "TALONSRX"
          inverted          		( true | false ) "false"
          sensorInverted    		( true | false ) "false"
          feedbackDevice    		( NONE | INTERNAL | QUADENCODER |  ANALOG |  
                                      TACHOMETER | PULSEWIDTHENCODERPOSITION  |  
                                      SENSORSUM |  SENSORDIFFERENCE |  
                                      REMOTESENSOR0 |  REMOTESENSOR1 | SOFTWAREEMULATEDSENSOR ) "NONE"
          countsPerRev      		CDATA "0"
          gearRatio         		CDATA "1"
          brakeMode         		( true | false ) "false"
          follow 					CDATA "-1"
          peakCurrentDuration 		CDATA #IMPLIED
          continuousCurrentLimit 	CDATA #IMPLIED
          peakCurrentLimit			CDATA #IMPLIED
          currentLimiting   		( true | false ) "false"  
          forwardlimitswitch        ( true | false ) "false" 
          forwardlimitswitchopen    ( true | false ) "true"        
          reverselimitswitch        ( true | false ) "false" 
          reverselimitswitchopen    ( true | false ) "true"        
>


<!-- digitalInput  -->
<!ELEMENT digitalInput EMPTY>
<!ATTLIST digitalInput 
          usage             ( TURRET_ANGLE_MIN | TURRET_ANGLE_MAX | HOPPER_BANNER_SENSOR ) "TURRET_ANGLE_MIN"
          digitalId         (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 ) "0"
          reversed          (true | false ) "false"
>

<!ELEMENT cancoder EMPTY >
<!ATTLIST cancoder
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
          offset    CDATA "0.0"
          reverse         ( true | false ) "false"
>

=== Team302/mainRepotest/src/main/config/practicechassis/xxx/robot.xml
<?xml version="1.0"?>
<!DOCTYPE robot SYSTEM "robot.dtd">
<robot>
	<pdp canId="0" />
	<pigeon canId="50"
               rotation="0.0" />

       <!--
	<limelight tablename="limelight"
                  mountingheight="20.0"
                  horizontaloffset="-10.0"
                  mountingangle="15.0"
                  rotation="0.0"
                  targetheight="120.0"
                  targetheight2="30.0"
                  defaultledmode="currentpipeline"
                  defaultcammode="vision"
                  streammode="sidebyside"
                  snapshots="off"
                  crosshairx="0.5"
                  crosshairy="0.5"
                  secondcrosshairx="0.25"
                  secondcrosshairy="0.25" />

	<blinkin position = "front" 
		  pwmId = "0"/>
  -->

<!-- ====================================================
     Chassis
     ====================================================  -->
    <swervechassis   type="SWERVE"
                     wheelBase="14.0"  
                     track="14.0"
                     maxVelocity="194.4"
                     maxAngularVelocity="1591.2"
                     maxAcceleration="24.0"
                     maxAngularAcceleration="24.0">
			 
        <swervemodule type="RIGHT_BACK"
                      turn_p="0.5"
                      turn_i="0.1"
                      turn_d="0.0"
                      turn_f="0.0"
                      turn_nominal_val="0.0"
                      turn_peak_val="1.0"
                      turn_max_acc="20"
                      turn_cruise_vel="50"
                      wheelDiameter="4.0"
>
            <motor  usage="DRIVE"
                    canId="3"
                    pdpID="3"
                    type="FALCON"
                    inverted="true"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="6.86"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>                  
             <motor  usage="TURN"
                    canId="2"
                    pdpID="2"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="8.4"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>        
		    <cancoder canId="2"
                            offset="-107.753906"/>
        </swervemodule>

        <swervemodule type="LEFT_BACK"
                      turn_p="0.5"
                      turn_i="0.1"
                      turn_d="0.0"
                      turn_f="0.0"
                      turn_nominal_val="0.0"
                      turn_peak_val="1.0"
                      turn_max_acc="10"
                      turn_cruise_vel="50"
			 wheelDiameter="4.0">
            <motor  usage="DRIVE"
                    canId="1"
                    pdpID="1"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="6.86"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>                  
             <motor usage="TURN"
                    canId="0"
                    pdpID="0"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="8.4"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>        
		    <cancoder canId="0"
                            offset="71.98242"/>
        </swervemodule>

        <swervemodule type="RIGHT_FRONT"
                      turn_p="0.5"
                      turn_i="0.1"
                      turn_d="0.0"
                      turn_f="0.0"
                      turn_nominal_val="0.0"
                      turn_peak_val="1.0"
                      turn_max_acc="10"
                      turn_cruise_vel="50"
			 wheelDiameter="4.0">
            <motor  usage="DRIVE"
                    canId="13"
                    pdpID="13"
                    type="FALCON"
                    inverted="true"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="6.86"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>                  
             <motor  usage="TURN"
                    canId="12"
                    pdpID="12"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="8.4"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>        
		    <cancoder canId="12"
                            offset="66.35742"/>
        </swervemodule>

        <swervemodule type="LEFT_FRONT"
                      turn_p="0.5"
                      turn_i="0.1"
                      turn_d="0.0"
                      turn_f="0.0"
                      turn_nominal_val="0.0"
                      turn_peak_val="1.0"
                      turn_max_acc="10"
                      turn_cruise_vel="50"
			 wheelDiameter="4.0">
            <motor  usage="DRIVE"
                    canId="15"
                    pdpID="15"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="6.86"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>                  
             <motor usage="TURN"
                    canId="14"
                    pdpID="14"
                    type="FALCON"
                    inverted="false"
                    sensorInverted="false"
                    feedbackDevice="INTERNAL"
                    countsPerRev="2048"
                    gearRatio="8.4"
                    brakeMode="true"
                    follow="-1"
                    peakCurrentDuration="15.0"
                    continuousCurrentLimit="40.0"
                    peakCurrentLimit="50.0"
                    currentLimiting="true" 
                    forwardlimitswitch="false"
                    forwardlimitswitchopen="true"
                    reverselimitswitch="false"
                    reverselimitswitchopen="true"/>        
		    <cancoder canId="14"
                            offset="133.242188"/>
        </swervemodule>

    </swervechassis>  
 
<!-- ====================================================
     Mechanisms
     ==================================================== --> 
     <!--   
	<mechanism type="INTAKE">
		<motor usage="INTAKE1"
                     canId="10"
                     pdpID="10"
                     type="FALCON"
                     inverted="false"
                     sensorInverted="false"
                     feedbackDevice="INTERNAL"
